# Generated by Django 6.0 on 2025-12-14 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observability', '0005_step5_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='apirequest',
            name='api_req_time_desc_idx',
        ),
    ]
