# Generated by Django 5.2.16 on 2026-07-16 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observability', '0015_rls_spans_and_force'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True)),
                ('service', models.CharField(db_index=True, max_length=200)),
                ('severity_text', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('severity_number', models.PositiveSmallIntegerField(default=0)),
                ('body', models.TextField(blank=True, default='')),
                ('trace_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('span_id', models.CharField(blank=True, default='', max_length=32)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('resource', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_records', to='tenancy.project')),
            ],
            options={
                'ordering': ['-time'],
                'indexes': [models.Index(fields=['service', '-time'], name='log_service_time_idx'), models.Index(fields=['trace_id'], name='log_trace_idx'), models.Index(fields=['project', '-time'], name='log_project_time_idx'), models.Index(condition=models.Q(('severity_number__gte', 17)), fields=['service', '-time'], name='log_error_service_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetricPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True)),
                ('service', models.CharField(db_index=True, max_length=200)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('kind', models.CharField(choices=[('gauge', 'gauge'), ('sum', 'sum'), ('histogram', 'histogram')], default='gauge', max_length=16)),
                ('unit', models.CharField(blank=True, default='', max_length=63)),
                ('value', models.FloatField(blank=True, null=True)),
                ('count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('sum_value', models.FloatField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('resource', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_points', to='tenancy.project')),
            ],
            options={
                'ordering': ['-time'],
                'indexes': [models.Index(fields=['service', 'name', '-time'], name='metric_svc_name_time_idx'), models.Index(fields=['project', '-time'], name='metric_project_time_idx')],
            },
        ),
    ]
