# Generated by Django 5.2.16 on 2026-07-16 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observability', '0017_metrics_logs_hypertable_rls'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('signature', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('service', models.CharField(blank=True, default='', max_length=200)),
                ('endpoint', models.CharField(blank=True, default='', max_length=255)),
                ('method', models.CharField(blank=True, default='', max_length=10)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sample_message', models.TextField(blank=True, default='')),
                (
                    'project',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='issues',
                        to='tenancy.project',
                    ),
                ),
            ],
            options={
                'ordering': ['-count', '-last_seen'],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('project', 'signature'), name='uniq_project_issue'
                    )
                ],
            },
        ),
    ]
