"""
Django settings for apm_platform project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()


def _env_bool_top(name: str, default: bool = False) -> bool:
    val = os.environ.get(name)
    if val is None:
        return default
    return val.strip().lower() in {"1", "true", "yes", "y", "on"}


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-insecure-secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool_top("DJANGO_DEBUG", default=True)

# Comma-separated: "localhost,127.0.0.1"
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,testserver").split(",")
    if h.strip()
]

# Comma-separated list of trusted origins for CSRF (include scheme + port).
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()
]

# Application definition

INSTALLED_APPS = [
    # Django default apps...
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "django_prometheus",
    "rest_framework",
    "django_filters",
    # Local
    "observability",
]


MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "apm_platform.db_middleware.DbRoleRoutingMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
]

ROOT_URLCONF = 'apm_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'apm_platform.wsgi.application'


# --- Database (env-first, docker-friendly) ---
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

RUNNING_TESTS = any(arg in sys.argv for arg in ["test", "pytest"])


def _env(name: str, default: str = "") -> str:
    return os.environ.get(name, default).strip()


def _env_bool(name: str, default: bool = False) -> bool:
    val = _env(name, "")
    if not val:
        return default
    return val.lower() in {"1", "true", "yes", "y", "on"}


def _split_host_port(raw: str, default_port: int) -> tuple[str, int]:
    value = raw.strip() if raw else ""
    if not value:
        return "localhost", default_port

    if value.startswith("["):
        host_part, _, rest = value[1:].partition("]")
        if not host_part:
            raise ValueError(f"Invalid host entry: {raw}")
        if not rest:
            return host_part, default_port
        if not rest.startswith(":"):
            raise ValueError(f"Invalid host entry: {raw}")
        port_part = rest[1:]
    else:
        if ":" in value:
            host_part, port_part = value.rsplit(":", 1)
        else:
            host_part = value
            port_part = str(default_port)

    try:
        port = int(port_part)
    except ValueError as exc:
        raise ValueError(f"Invalid port in host entry: {raw}") from exc

    return host_part, port


def _parse_host_list(raw: str, default_port: int) -> list[tuple[str, int]]:
    entries = [entry.strip() for entry in raw.split(",") if entry.strip()]
    return [_split_host_port(entry, default_port) for entry in entries]


FORCE_SQLITE = _env_bool("FORCE_SQLITE", False)

POSTGRES_NAME = _env("POSTGRES_DB") or _env("DB_NAME")
POSTGRES_HOST = _env("POSTGRES_HOST") or _env("DB_HOST", "localhost")
POSTGRES_PORT = _env("POSTGRES_PORT") or _env("DB_PORT", "5432")

ADMIN_USER = _env("POSTGRES_USER") or _env("DB_USER")
ADMIN_PASSWORD = _env("POSTGRES_PASSWORD") or _env("DB_PASSWORD")

WRITER_USER = _env("POSTGRES_WRITER_USER") or _env("POSTGRES_APP_USER") or ADMIN_USER
WRITER_PASSWORD = (
    _env("POSTGRES_WRITER_PASSWORD") or _env("POSTGRES_APP_PASSWORD") or ADMIN_PASSWORD
)

READER_USER = _env("POSTGRES_READER_USER") or _env("POSTGRES_READONLY_USER") or WRITER_USER
READER_PASSWORD = (
    _env("POSTGRES_READER_PASSWORD") or _env("POSTGRES_READONLY_PASSWORD") or WRITER_PASSWORD
)

if not ADMIN_USER:
    ADMIN_USER = WRITER_USER
if not ADMIN_PASSWORD:
    ADMIN_PASSWORD = WRITER_PASSWORD

CLUSTER_DB_PRIMARY_HOST = _env("CLUSTER_DB_PRIMARY_HOST") or POSTGRES_HOST
CLUSTER_DB_REPLICA_HOSTS = _env("CLUSTER_DB_REPLICA_HOSTS")

# Optional SSL mode for hosted Postgres (examples: disable, require, verify-ca, verify-full)
DB_SSLMODE = _env("DB_SSLMODE")
DB_OPTIONS = {"sslmode": DB_SSLMODE} if DB_SSLMODE else {}
READ_AFTER_WRITE_TTL = int(_env("READ_AFTER_WRITE_TTL", "2") or "2")

HAS_POSTGRES_ENV = all([POSTGRES_NAME, WRITER_USER, WRITER_PASSWORD])

REPLICA_DATABASES: list[str] = []

if (not FORCE_SQLITE) and HAS_POSTGRES_ENV:
    primary_host, primary_port = _split_host_port(
        CLUSTER_DB_PRIMARY_HOST, int(POSTGRES_PORT or "5432")
    )
    default_db = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": POSTGRES_NAME,
        "USER": ADMIN_USER,
        "PASSWORD": ADMIN_PASSWORD,
        "HOST": primary_host,
        "PORT": str(primary_port),
        "CONN_MAX_AGE": int(os.environ.get("DB_CONN_MAX_AGE", "60")),
        # psycopg/Django expects a dict here
        "OPTIONS": DB_OPTIONS,
        "TEST": {
            "NAME": _env("POSTGRES_TEST_DB", f"{POSTGRES_NAME}_test"),
        },
    }
    writer_db = default_db.copy()
    writer_db["USER"] = WRITER_USER
    writer_db["PASSWORD"] = WRITER_PASSWORD

    reader_db = default_db.copy()
    reader_db["USER"] = READER_USER
    reader_db["PASSWORD"] = READER_PASSWORD

    DATABASES = {
        "default": default_db,
        "writer": writer_db,
        "reader": reader_db,
    }

    if CLUSTER_DB_REPLICA_HOSTS:
        for idx, (host, port) in enumerate(
            _parse_host_list(CLUSTER_DB_REPLICA_HOSTS, primary_port), start=1
        ):
            alias = f"replica_{idx}"
            replica_db = reader_db.copy()
            replica_db["HOST"] = host
            replica_db["PORT"] = str(port)
            DATABASES[alias] = replica_db
            REPLICA_DATABASES.append(alias)

    DATABASE_ROUTERS = ["apm_platform.db_router.PrimaryReplicaRouter"]
else:
    # SQLite fallback (great for quick local runs / CI without Postgres)
    BASE_DIR = globals().get("BASE_DIR")  # in case you already defined it above
    if BASE_DIR is None:
        from pathlib import Path

        BASE_DIR = Path(__file__).resolve().parent.parent

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": ":memory:" if RUNNING_TESTS else (BASE_DIR / "db.sqlite3"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.environ.get("DJANGO_TIME_ZONE", "UTC")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# WhiteNoise: collectstatic output directory (served by WhiteNoise)
STATIC_ROOT = BASE_DIR / "staticfiles"

# Django 4.2+ (incl. Django 6): configure staticfiles backend via STORAGES
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Backward-compatible setting (may be deprecated on newer Django)
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Test runner can be overridden for CI/reporting (e.g., xmlrunner)
TEST_RUNNER = os.environ.get("DJANGO_TEST_RUNNER", "django.test.runner.DiscoverRunner")
# If using xmlrunner, this directs where JUnit XML files are written
TEST_OUTPUT_DIR = os.environ.get("TEST_OUTPUT_DIR")

# --- Django REST Framework defaults ---
REST_FRAMEWORK = {
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.OrderingFilter",
        "rest_framework.filters.SearchFilter",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": int(os.environ.get("DRF_PAGE_SIZE", "50")),
    "TEST_REQUEST_DEFAULT_FORMAT": "json",
}

# --- APM ingestion defaults (Step 2) ---
# Used by /api/requests/ingest/ (can be overridden via query params)
APM_INGEST_BATCH_SIZE = 1000  # bulk_create batch size
APM_INGEST_MAX_EVENTS = 50_000  # max number of events accepted per request
APM_INGEST_MAX_ERRORS = 25  # max number of per-item error details returned

# SSL/HTTPS Security Settings
# Enable SSL redirect when nginx with SSL is available (production or local with nginx)
SECURE_SSL_REDIRECT = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Exempt health endpoint from SSL redirect (for Railway healthcheck)
SECURE_REDIRECT_EXEMPT = [r"^/api/health/$", r"^/metrics/$"]
