"""
Django settings for apm_platform project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import sys

def _env_bool_top(name: str, default: bool = False) -> bool:
    val = os.environ.get(name)
    if val is None:
        return default
    return val.strip().lower() in {"1", "true", "yes", "y", "on"}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-insecure-secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool_top("DJANGO_DEBUG", default=True)

# Comma-separated: "localhost,127.0.0.1"
ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") if h.strip()
]

# Application definition

INSTALLED_APPS = [
    # Django default apps...
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party
    "rest_framework",
    "django_filters",

    # Local
    "observability",
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'apm_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'apm_platform.wsgi.application'


# --- Database (env-first, docker-friendly) ---
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

RUNNING_TESTS = any(arg in sys.argv for arg in ["test", "pytest"])

def _env(name: str, default: str = "") -> str:
    return os.environ.get(name, default).strip()

def _env_bool(name: str, default: bool = False) -> bool:
    val = _env(name, "")
    if not val:
        return default
    return val.lower() in {"1", "true", "yes", "y", "on"}

FORCE_SQLITE = _env_bool("FORCE_SQLITE", False)

POSTGRES_NAME = _env("POSTGRES_DB") or _env("DB_NAME")
POSTGRES_USER = _env("POSTGRES_USER") or _env("DB_USER")
POSTGRES_PASSWORD = _env("POSTGRES_PASSWORD") or _env("DB_PASSWORD")
POSTGRES_HOST = _env("POSTGRES_HOST") or _env("DB_HOST", "localhost")
POSTGRES_PORT = _env("POSTGRES_PORT") or _env("DB_PORT", "5432")

# Optional SSL mode for hosted Postgres (examples: disable, require, verify-ca, verify-full)
DB_SSLMODE = _env("DB_SSLMODE")
DB_OPTIONS = {"sslmode": DB_SSLMODE} if DB_SSLMODE else {}

HAS_POSTGRES_ENV = all([POSTGRES_NAME, POSTGRES_USER, POSTGRES_PASSWORD])

if (not FORCE_SQLITE) and HAS_POSTGRES_ENV:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": POSTGRES_NAME,
            "USER": POSTGRES_USER,
            "PASSWORD": POSTGRES_PASSWORD,
            "HOST": POSTGRES_HOST,
            "PORT": POSTGRES_PORT,
            "CONN_MAX_AGE": int(os.environ.get("DB_CONN_MAX_AGE", "60")),
            # psycopg/Django expects a dict here
            "OPTIONS": DB_OPTIONS,
            "TEST": {
                "NAME": _env("POSTGRES_TEST_DB", f"{POSTGRES_NAME}_test"),
            },
        }
    }
else:
    # SQLite fallback (great for quick local runs / CI without Postgres)
    BASE_DIR = globals().get("BASE_DIR")  # in case you already defined it above
    if BASE_DIR is None:
        from pathlib import Path
        BASE_DIR = Path(__file__).resolve().parent.parent

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": ":memory:" if RUNNING_TESTS else (BASE_DIR / "db.sqlite3"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.environ.get("DJANGO_TIME_ZONE", "UTC")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# WhiteNoise: collectstatic output directory (served by WhiteNoise)
STATIC_ROOT = BASE_DIR / "staticfiles"

# Django 4.2+ (incl. Django 6): configure staticfiles backend via STORAGES
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Backward-compatible setting (may be deprecated on newer Django)
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# --- Django REST Framework defaults ---
REST_FRAMEWORK = {
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.OrderingFilter",
        "rest_framework.filters.SearchFilter",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": int(os.environ.get("DRF_PAGE_SIZE", "50")),
    "TEST_REQUEST_DEFAULT_FORMAT": "json",
}

# --- APM ingestion defaults (Step 2) ---
# Used by /api/requests/ingest/ (can be overridden via query params)
APM_INGEST_BATCH_SIZE = 1000       # bulk_create batch size
APM_INGEST_MAX_EVENTS = 50_000     # max number of events accepted per request
APM_INGEST_MAX_ERRORS = 25         # max number of per-item error details returned
