"""
Django settings for apm_platform project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

from dotenv import load_dotenv

from apm_platform.env import env, env_bool, env_csv, parse_host_list, split_host_port

# Load environment variables from .env file
load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-insecure-secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", default=False)

# Comma-separated: "localhost,127.0.0.1"
ALLOWED_HOSTS = env_csv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,testserver")

# Comma-separated list of trusted origins for CSRF (include scheme + port).
CSRF_TRUSTED_ORIGINS = env_csv("DJANGO_CSRF_TRUSTED_ORIGINS")

# Application definition

INSTALLED_APPS = [
    # Django default apps...
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "django_prometheus",
    "rest_framework",
    "django_filters",
    "drf_spectacular",
    # Local
    "tenancy",
    "observability",
    "notifications",
    "alerting",
    "dora",
]


MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "apm_platform.db_middleware.DbRoleRoutingMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "tenancy.middleware.TenantContextMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
]

ROOT_URLCONF = 'apm_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'apm_platform.wsgi.application'


# --- Database (env-first, docker-friendly) ---
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

RUNNING_TESTS = any(arg in sys.argv for arg in ["test", "pytest"])

# PostgreSQL + TimescaleDB is the ONE and only backend. TimescaleDB and pgvector
# are Postgres extensions, so "Postgres + TimescaleDB + pgvector" is a single
# engine — dev, CI, and production all run it, and behaviour is identical
# everywhere (no SQLite path, no feature skips, tests match prod exactly).
#
# Values default to the local docker-compose credentials so DB-less management
# commands (check, makemigrations --check, collectstatic) work without any env
# set; anything that runs queries needs a real Postgres reachable via these.
POSTGRES_NAME = env("POSTGRES_DB") or env("DB_NAME") or "apm"
POSTGRES_HOST = env("POSTGRES_HOST") or env("DB_HOST", "localhost")
POSTGRES_PORT = env("POSTGRES_PORT") or env("DB_PORT", "5432")

ADMIN_USER = env("POSTGRES_USER") or env("DB_USER") or "apm"
ADMIN_PASSWORD = env("POSTGRES_PASSWORD") or env("DB_PASSWORD") or "apm"

WRITER_USER = env("POSTGRES_WRITER_USER") or env("POSTGRES_APP_USER") or ADMIN_USER
WRITER_PASSWORD = env("POSTGRES_WRITER_PASSWORD") or env("POSTGRES_APP_PASSWORD") or ADMIN_PASSWORD

READER_USER = env("POSTGRES_READER_USER") or env("POSTGRES_READONLY_USER") or WRITER_USER
READER_PASSWORD = (
    env("POSTGRES_READER_PASSWORD") or env("POSTGRES_READONLY_PASSWORD") or WRITER_PASSWORD
)

CLUSTER_DB_PRIMARY_HOST = env("CLUSTER_DB_PRIMARY_HOST") or POSTGRES_HOST
CLUSTER_DB_REPLICA_HOSTS = env("CLUSTER_DB_REPLICA_HOSTS")

# Optional SSL mode for hosted Postgres (examples: disable, require, verify-ca, verify-full)
DB_SSLMODE = env("DB_SSLMODE")
DB_OPTIONS = {"sslmode": DB_SSLMODE} if DB_SSLMODE else {}
READ_AFTER_WRITE_TTL = int(env("READ_AFTER_WRITE_TTL", "2") or "2")

REPLICA_DATABASES: list[str] = []

primary_host, primary_port = split_host_port(CLUSTER_DB_PRIMARY_HOST, int(POSTGRES_PORT or "5432"))
default_db = {
    "ENGINE": "django.db.backends.postgresql",
    "NAME": POSTGRES_NAME,
    "USER": ADMIN_USER,
    "PASSWORD": ADMIN_PASSWORD,
    "HOST": primary_host,
    "PORT": str(primary_port),
    "CONN_MAX_AGE": int(os.environ.get("DB_CONN_MAX_AGE", "60")),
    # psycopg/Django expects a dict here
    "OPTIONS": DB_OPTIONS,
    "TEST": {
        "NAME": env("POSTGRES_TEST_DB", f"{POSTGRES_NAME}_test"),
    },
}
writer_db = default_db.copy()
writer_db["USER"] = WRITER_USER
writer_db["PASSWORD"] = WRITER_PASSWORD

reader_db = default_db.copy()
reader_db["USER"] = READER_USER
reader_db["PASSWORD"] = READER_PASSWORD

DATABASES = {
    "default": default_db,
    "writer": writer_db,
    "reader": reader_db,
}

if CLUSTER_DB_REPLICA_HOSTS:
    for idx, (host, port) in enumerate(
        parse_host_list(CLUSTER_DB_REPLICA_HOSTS, primary_port), start=1
    ):
        alias = f"replica_{idx}"
        replica_db = reader_db.copy()
        replica_db["HOST"] = host
        replica_db["PORT"] = str(port)
        DATABASES[alias] = replica_db
        REPLICA_DATABASES.append(alias)

# The router sends writes to "writer" and reads to "reader"/replicas. Django's
# TestCase only permits queries on "default" unless every test class opts in via
# `databases`, so with the router installed each write raises
# DatabaseOperationForbidden. All three aliases address the same physical
# database (writer/reader differ only in credentials) and there are no replicas
# under test, so skipping the router under tests keeps a single-connection view
# instead of exercising a split that does not exist here.
if not RUNNING_TESTS:
    DATABASE_ROUTERS = ["apm_platform.db_router.PrimaryReplicaRouter"]


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.environ.get("DJANGO_TIME_ZONE", "UTC")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# WhiteNoise: collectstatic output directory (served by WhiteNoise)
STATIC_ROOT = BASE_DIR / "staticfiles"

# Django 4.2+ (incl. Django 6): configure staticfiles backend via STORAGES
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Backward-compatible setting (may be deprecated on newer Django)
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Test runner can be overridden for CI/reporting (e.g., xmlrunner)
TEST_RUNNER = os.environ.get("DJANGO_TEST_RUNNER", "django.test.runner.DiscoverRunner")
# If using xmlrunner, this directs where JUnit XML files are written
TEST_OUTPUT_DIR = os.environ.get("TEST_OUTPUT_DIR")

# --- Django REST Framework defaults ---
REST_FRAMEWORK = {
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.OrderingFilter",
        "rest_framework.filters.SearchFilter",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": int(os.environ.get("DRF_PAGE_SIZE", "50")),
    "TEST_REQUEST_DEFAULT_FORMAT": "json",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # Multi-tenant auth (Phase 5): scoped API keys for ingestion, JWT for the
    # dashboard/API, session for the browsable admin. Order matters — API key is
    # tried first and bails out cleanly if the header keyword doesn't match.
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "tenancy.authentication.ApiKeyAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    # Endpoints stay open by default (ingestion/analytics are currently public);
    # tenant-scoped views opt in via explicit permission_classes.
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
}

from datetime import timedelta as _timedelta  # noqa: E402

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": _timedelta(minutes=int(os.environ.get("JWT_ACCESS_MINUTES", "30"))),
    "REFRESH_TOKEN_LIFETIME": _timedelta(days=int(os.environ.get("JWT_REFRESH_DAYS", "7"))),
    "ROTATE_REFRESH_TOKENS": True,
}

# --- OpenAPI schema (drf-spectacular) ---
SPECTACULAR_SETTINGS = {
    "TITLE": "APM Observability API",
    "DESCRIPTION": (
        "Application Performance Monitoring backend: batch ingestion of API "
        "request events, time-series analytics (hourly/daily aggregates, KPIs, "
        "top endpoints), and semantic search over errors."
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
}

# --- APM ingestion defaults (Step 2) ---
# Used by /api/requests/ingest/ (can be overridden via query params)
APM_INGEST_BATCH_SIZE = 1000  # bulk_create batch size
APM_INGEST_MAX_EVENTS = 50_000  # max number of events accepted per request
APM_INGEST_MAX_ERRORS = 25  # max number of per-item error details returned

# SSL/HTTPS Security Settings
# Keep local/test defaults HTTP-friendly; enable strict HTTPS via env in docker/prod.
SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", default=False)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https") if SECURE_SSL_REDIRECT else None
SESSION_COOKIE_SECURE = env_bool("DJANGO_SESSION_COOKIE_SECURE", default=SECURE_SSL_REDIRECT)
CSRF_COOKIE_SECURE = env_bool("DJANGO_CSRF_COOKIE_SECURE", default=SECURE_SSL_REDIRECT)

# Exempt health endpoint from SSL redirect (for Railway healthcheck)
SECURE_REDIRECT_EXEMPT = [r"^api/health/$", r"^metrics/?$"]

# ---------------------------------------------------------------------------
# Observability: structured JSON logging correlated with traces
# ---------------------------------------------------------------------------
LOG_LEVEL = os.environ.get("DJANGO_LOG_LEVEL", "INFO").upper()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "trace_context": {
            "()": "apm_platform.logging_utils.TraceContextFilter",
        },
    },
    "formatters": {
        "json": {
            "()": "pythonjsonlogger.jsonlogger.JsonFormatter",
            "format": "%(asctime)s %(levelname)s %(name)s %(message)s %(trace_id)s %(span_id)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "filters": ["trace_context"],
            "formatter": "json",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
}

# ---------------------------------------------------------------------------
# Observability: distributed tracing (OpenTelemetry -> Collector -> Tempo)
# Disabled unless OTEL_ENABLED is truthy; never affects tests/CI.
# ---------------------------------------------------------------------------
OTEL_ENABLED = env_bool("OTEL_ENABLED", default=False)
if OTEL_ENABLED:
    from apm_platform.tracing import configure_tracing

    configure_tracing()
