# Generated by Django 5.2.16 on 2026-07-16 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('kind', models.CharField(choices=[('threshold', 'threshold'), ('anomaly', 'anomaly')], default='threshold', max_length=16)),
                ('metric', models.CharField(choices=[('error_rate', 'error rate'), ('latency_avg', 'avg latency (ms)'), ('latency_p95', 'p95 latency (ms)'), ('request_count', 'request count')], default='error_rate', max_length=20)),
                ('service', models.CharField(blank=True, default='', max_length=100)),
                ('endpoint', models.CharField(blank=True, default='', max_length=255)),
                ('comparator', models.CharField(choices=[('gt', '>'), ('gte', '>='), ('lt', '<'), ('lte', '<=')], default='gt', max_length=4)),
                ('threshold', models.FloatField(default=0.0)),
                ('z_threshold', models.FloatField(default=3.0)),
                ('window_minutes', models.PositiveIntegerField(default=5)),
                ('severity', models.CharField(choices=[('critical', 'critical'), ('warning', 'warning'), ('info', 'info')], default='warning', max_length=16)),
                ('runbook_url', models.URLField(blank=True, default='', max_length=1024)),
                ('state', models.CharField(choices=[('ok', 'ok'), ('firing', 'firing')], db_index=True, default='ok', max_length=8)),
                ('last_value', models.FloatField(blank=True, null=True)),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='tenancy.project')),
            ],
            options={
                'ordering': ['project', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AlertRuleEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('firing', models.BooleanField(default=False)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='alerting.alertrule')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.AddConstraint(
            model_name='alertrule',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uniq_project_alertrule'),
        ),
    ]
