# Control node overrides (optional)
# control_node_ip: 198.51.100.11
# minio_root_user: apm_backup
# minio_root_password: change-me
# minio_bucket: pgbackrest
# minio_bucket_cold: pgbackrest-cold
# pgbackrest_cipher_pass: CHANGE_ME
