apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "apm.fullname" . }}-config
  labels:
    {{- include "apm.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  POSTGRES_HOST: {{ include "apm.postgresHost" . | quote }}
