# Generated by Django 5.2.16 on 2026-07-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    'fingerprint',
                    models.CharField(blank=True, db_index=True, default='', max_length=128),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('firing', 'firing'), ('resolved', 'resolved')],
                        db_index=True,
                        default='firing',
                        max_length=16,
                    ),
                ),
                (
                    'severity',
                    models.CharField(
                        choices=[
                            ('critical', 'critical'),
                            ('warning', 'warning'),
                            ('info', 'info'),
                            ('unknown', 'unknown'),
                        ],
                        db_index=True,
                        default='unknown',
                        max_length=16,
                    ),
                ),
                (
                    'alertname',
                    models.CharField(blank=True, db_index=True, default='', max_length=255),
                ),
                ('summary', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('runbook_url', models.URLField(blank=True, default='', max_length=1024)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('annotations', models.JSONField(blank=True, default=dict)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('channels', models.JSONField(blank=True, default=list)),
                ('delivered', models.BooleanField(db_index=True, default=False)),
                ('delivery_error', models.TextField(blank=True, default='')),
                ('raw', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [
                    models.Index(fields=['severity', '-received_at'], name='notif_sev_time_idx'),
                    models.Index(fields=['status', '-received_at'], name='notif_status_time_idx'),
                    models.Index(fields=['alertname', '-received_at'], name='notif_alert_time_idx'),
                ],
            },
        ),
    ]
